[[media]]
name = "bulletty-archlinux-install.jpg"
datetime = "2026-02-23T10:06:59"

[[media]]
name = "bulletty1.gif"
datetime = "2025-07-02T13:34:57"

[[media]]
name = "bulletty8.gif"
datetime = "2025-11-07T13:16:07"

[[media]]
name = "clone_stacking_rg351v.jpg"
datetime = "2026-02-23T10:05:48"

[[media]]
name = "custom-funbox-pedal.jpg"
datetime = "2026-02-23T10:09:08"

[[media]]
name = "funbox-testing.webm"
datetime = "2026-02-23T10:15:34"
