[[media]]
name = "bulletty-archlinux-install.jpg"
datetime = "2026-02-10T10:06:59"

[[media]]
name = "bulletty1.gif"
datetime = "2025-07-02T13:34:57"

[[media]]
name = "bulletty8.gif"
datetime = "2025-11-07T13:16:07"

[[media]]
name = "clone_stacking_rg351v.jpg"
datetime = "2024-05-30T10:05:48"

[[media]]
name = "custom-funbox-pedal.jpg"
datetime = "2025-11-15T10:09:08"

[[media]]
name = "funbox-testing.webm"
datetime = "2025-12-13T10:15:34"

[[media]]
name = "changing-guitar-strings.jpg"
datetime = "2025-05-20T21:56:32"

[[media]]
name = "flipperzero-feed-reader.jpg"
datetime = "2025-04-29T23:15:41"

[[media]]
name = "flipperzero-feed-reader2.jpg"
datetime = "2025-04-29T23:17:18"

[[media]]
name = "funbox-burned-capacitor.jpg"
datetime = "2025-07-24T19:50:31"

[[media]]
name = "microcontroller-as-wifi-module-for-flipperzero.jpg"
datetime = "2025-04-07T23:47:13"

[[media]]
name = "soldering-funbox-pedal.webm"
datetime = "2025-07-24T16:39:02"

[[media]]
name = "watercolor-painting.jpg"
datetime = "2025-01-15T20:28:05"
