[[media]]
name = "bulletty-archlinux-install.jpg"
datetime = "2026-02-10T10:06:59"

[[media]]
name = "bulletty8.gif"
datetime = "2025-11-07T13:16:07"

[[media]]
name = "clone_stacking_rg351v.jpg"
datetime = "2024-05-30T10:05:48"

[[media]]
name = "custom-funbox-pedal.jpg"
datetime = "2025-11-15T10:09:08"

[[media]]
name = "funbox-testing.webm"
datetime = "2025-12-13T10:15:34"

[[media]]
name = "changing-guitar-strings.jpg"
datetime = "2025-05-20T21:56:32"

[[media]]
name = "flipperzero-feed-reader.jpg"
datetime = "2025-04-29T23:15:41"

[[media]]
name = "flipperzero-feed-reader2.jpg"
datetime = "2025-04-29T23:17:18"

[[media]]
name = "funbox-burned-capacitor.jpg"
datetime = "2025-07-24T19:50:31"

[[media]]
name = "microcontroller-as-wifi-module-for-flipperzero.jpg"
datetime = "2025-04-07T23:47:13"

[[media]]
name = "soldering-funbox-pedal.webm"
datetime = "2025-07-24T16:39:02"

[[media]]
name = "watercolor-painting.jpg"
datetime = "2025-01-15T20:28:05"

[[media]]
name = "7x7x7cube.jpg"
datetime = "2020-10-07T16:29:09"

[[media]]
name = "fixing-looper-pedal.jpg"
datetime = "2022-09-23T16:21:32"

[[media]]
name = "fixing-old-record-player.jpg"
datetime = "2023-05-18T12:32:48"

[[media]]
name = "gameboy-camera-laptop.jpg"
datetime = "2023-03-24T10:50:57"

[[media]]
name = "old-duesseldorf-apartment-desk.jpg"
datetime = "2020-12-22T12:05:11"

[[media]]
name = "old-manaus-apartment-office0.jpg"
datetime = "2017-08-20T15:24:02"

[[media]]
name = "old-manaus-apartment-office1.jpg"
datetime = "2017-12-21T15:22:39"

[[media]]
name = "old-unity-drifting-racing-game.webm"
datetime = "2020-01-12T14:28:26"

[[media]]
name = "reading-the-c-debugging-book.jpg"
datetime = "2020-05-25T20:24:25"

[[media]]
name = "testing-steamdeck-desktop.jpg"
datetime = "2023-01-26T20:53:36"

[[media]]
name = "bombinha-racket-level-editor.webm"
datetime = "2023-11-02T14:32:32"

[[media]]
name = "night-trash-shader.webm"
datetime = "2020-03-14T12:41:52"

[[media]]
name = "steamdeck-issue.webm"
datetime = "2022-06-28T20:45:58"

[[media]]
name = "testing-2048-bootloader.webm"
datetime = "2020-06-26T23:56:49"

[[media]]
name = "annileen-editor-running-on-steamdeck.jpg"
datetime = "2025-09-13T14:04:54"

[[media]]
name = "bulletty-running-on-android.webm"
datetime = "2025-11-25T15:05:01"

[[media]]
name = "funbox-testing-guitar.jpg"
datetime = "2025-10-24T22:35:39"

[[media]]
name = "wordlos-development.webm"
datetime = "2022-03-02T19:13:32"

[[media]]
name = "an-online-tictactoe-written-c-allegro.jpg"
datetime = "2008-07-10T16:44:21"

[[media]]
name = "apply-to-production.jpg"
datetime = "2018-03-14T16:45:49"

[[media]]
name = "black-river-studios-merch.jpg"
datetime = "2015-09-26T16:47:56"

[[media]]
name = "replicating-fortnite-destroy1.mp4"
datetime = "2018-07-11T15:52:10"

[[media]]
name = "replicating-fortnite-destroy2.mp4"
datetime = "2018-07-12T15:52:31"

[[media]]
name = "clonecraft-first-cube.mp4"
datetime = "2018-09-24T15:53:13"

[[media]]
name = "mode7-shipgame.mp4"
datetime = "2018-04-22T15:51:31"

[[media]]
name = "racing-game-prototype-shader-world-deform.mp4"
datetime = "2022-03-15T16:20:12"

[[media]]
name = "bulletty_cover.png"
datetime = "2025-10-14T13:51:45"

[[media]]
name = "testing-nes-development.png"
datetime = "2022-05-14T16:18:31"

[[media]]
name = "conflict-0-revolution-game.jpg"
datetime = "2018-10-13T17:27:59"

[[media]]
name = "conflict-0-revolution-title-and-button.jpg"
datetime = "2018-10-13T17:27:59"

[[media]]
name = "raytracing-in-one-weekend.png"
datetime = "2019-01-23T16:29:11"

[[media]]
name = "retro2048-development-screen.jpg"
datetime = "2020-06-07T17:30:08"

[[media]]
name = "conflict-0-shattered-intro.mp4"
datetime = "2018-10-13T16:08:17"

[[media]]
name = "master-of-puppets-shader.mp4"
datetime = "2019-01-18T16:10:55"

[[media]]
name = "coin-shader.mp4"
datetime = "2019-04-03T16:10:32"

[[media]]
name = "clonecraf-bug.mp4"
datetime = "2018-05-12T16:09:27"

[[media]]
name = "clonecraft-creating-floor-mesh.mp4"
datetime = "2018-12-07T16:12:03"

[[media]]
name = "clonecraft-first-world-render.mp4"
datetime = "2018-12-14T16:11:34"

[[media]]
name = "clonecraft-minecraft-world.mp4"
datetime = "2018-12-21T16:11:18"

[[media]]
name = "chess-pawns-shader.mp4"
datetime = "2019-05-31T16:10:15"

[[media]]
name = "mitosis-duplicating-cubes.mp4"
datetime = "2019-02-02T16:14:37"

[[media]]
name = "mitosis-floor-scale.mp4"
datetime = "2019-02-02T16:14:37"

[[media]]
name = "mitosis-level-4.mp4"
datetime = "2019-02-02T16:14:37"

[[media]]
name = "mitosis-level3.mp4"
datetime = "2019-02-02T16:14:37"

[[media]]
name = "sdf-shader-curtains.mp4"
datetime = "2019-12-20T16:15:01"

[[media]]
name = "sdf-shader-volumetric-light.jpg"
datetime = "2019-12-20T16:13:01"

[[media]]
name = "sdf-shader-window.mp4"
datetime = "2019-12-19T16:09:47"

[[media]]
name = "improvised-standing-desk-during-pandemic.jpg"
datetime = "2020-03-23T17:41:58"

[[media]]
name = "annileen-shader-hotreload.mp4"
datetime = "2021-11-16T16:22:24"

[[media]]
name = "annileen-editor.mp4"
datetime = "2021-10-13T16:52:43"

[[media]]
name = "blue-oyster-cult-shader.mp4"
datetime = "2019-10-10T16:15:48"

[[media]]
name = "javascript-coroutines.mp4"
datetime = "2019-08-09T16:16:15"

[[media]]
name = "sdf-shader-window-test.mp4"
datetime = "2019-12-20T16:16:57"

[[media]]
name = "retro2048-test.mp4"
datetime = "2020-06-09T16:18:21"

[[media]]
name = "wordlos-wordle-for-dos-working.mp4"
datetime = "2022-03-08T16:18:50"

[[media]]
name = "prior-catharsis-game-sdf-rendering.mp4"
datetime = "2019-08-04T16:16:33"

[[media]]
name = "spacebar-clicker-js13kgames.mp4"
datetime = "2021-09-13T16:58:57"

[[media]]
name = "spacebar-clicker-mobile.png"
datetime = "2021-09-21T16:58:21"

[[media]]
name = "lowrezjam-processing-p5js.mp4"
datetime = "2021-08-05T17:59:42"

[[media]]
name = "sdf-scene-on-the-sea.mp4"
datetime = "2020-09-15T17:58:39"

[[media]]
name = "doomoji-first-test.mp4"
datetime = "2020-08-28T18:01:16"

[[media]]
name = "doomoji-second-test.mp4"
datetime = "2020-08-29T18:01:59"

[[media]]
name = "batman-mvp.png"
datetime = "2020-07-18T18:03:44"

[[media]]
name = "debugging-retro2048-with-insight.png"
datetime = "2020-06-21T18:04:33"

[[media]]
name = "issue-programming-for-wasm4.png"
datetime = "2022-10-01T18:08:32"

[[media]]
name = "rendering-doom-with-emojis-on-hackernews.jpg"
datetime = "2022-11-12T19:10:20"

[[media]]
name = "terrible-error-c.png"
datetime = "2022-10-01T18:09:21"

[[media]]
name = "wordlos-with-crt-shader.mp4"
datetime = "2022-12-17T08:43:20"

[[media]]
name = "advent-of-code-2022-in-racket.jpg"
datetime = "2022-12-09T09:44:15"

[[media]]
name = "spacelord-x-first-movement-particles.mp4"
datetime = "2022-10-01T08:46:42"

[[media]]
name = "spacelord-x-core-shield.mp4"
datetime = "2022-10-02T08:48:07"

[[media]]
name = "spacelord-x-final-submition.mp4"
datetime = "2022-10-03T08:49:21"

[[media]]
name = "spacelord-x-mobile-gameplay.mp4"
datetime = "2022-10-04T08:50:42"

[[media]]
name = "spacelord-x-runs-mobile.jpg"
datetime = "2022-10-03T08:50:09"

[[media]]
name = "saving-timelapse-ubuntu-gnome-wayland.mp4"
datetime = "2024-04-09T08:51:51"

[[media]]
name = "clone-stacking-written-in-fennel.jpg"
datetime = "2024-04-13T08:52:47"

[[media]]
name = "clutterlog-naive-processing-vs-rayon-loop.png"
datetime = "2026-02-24T09:50:07"

[[media]]
name = "clutterlog-example.webm"
datetime = "2026-02-24T13:24:32"
